#!/usr/bin/env node
/**
 * evolve.js — Skepsis Self-Improvement Engine
 * 
 * Usage: node scripts/evolve.js --lesson "Lesson text" [--section "Section Name"]
 * 
 * Reads the current canonical prompt and lessons-learned.md, produces a
 * structured proposal with exact edits. Human review required before applying.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const CANONICAL = path.join(ROOT, "src", "Universal-Debunking-Article-Prompt.md");
const LESSONS = path.join(ROOT, "lessons-learned.md");
const PROPOSAL = path.join(ROOT, "proposed-changes.md");

function formatDate() {
  return new Date().toISOString().split("T")[0];
}

function main() {
  const args = process.argv.slice(2);
  const lessonIdx = args.indexOf("--lesson");
  const sectionIdx = args.indexOf("--section");

  if (lessonIdx === -1 || !args[lessonIdx + 1]) {
    console.error("Usage: node evolve.js --lesson \"Your lesson here\" [--section \"Target Section\"]");
    process.exit(1);
  }

  const lesson = args[lessonIdx + 1];
  const section = sectionIdx !== -1 ? args[sectionIdx + 1] : null;

  // Read canonical version
  let canonicalVersion = "unknown";
  if (fs.existsSync(CANONICAL)) {
    const content = fs.readFileSync(CANONICAL, "utf8");
    const match = content.match(/Version (\d+\.\d+)/);
    if (match) canonicalVersion = match[1];
  }

  // Append to lessons-learned.md
  const lessonEntry = `\n## ${formatDate()} — v${canonicalVersion}\n\n- **Lesson:** ${lesson}\n${section ? `- **Suggested section:** ${section}\n` : ""}- **Status:** Open\n`;
  
  if (!fs.existsSync(LESSONS)) {
    fs.writeFileSync(LESSONS, "# Skepsis Lessons Learned\n\nRunning log of insights from investigations that should feed back into the framework.\n");
  }
  fs.appendFileSync(LESSONS, lessonEntry);
  console.log(`📝 Lesson logged to lessons-learned.md`);

  // Generate proposal
  const proposal = `# Skepsis Proposed Changes
> Generated: ${formatDate()} | Framework: v${canonicalVersion}

## Lesson
${lesson}

## Affected Files
- \`src/Universal-Debunking-Article-Prompt.md\` (canonical master)
- \`src/Universal-Debunking-System-Prompt.md\` (derive via build)
- \`src/Universal-Debunking-User-Prompt.md\` (derive via build)

## Candidate Edits

### Option A: Append to Existing Section
${section ? `If the lesson maps cleanly to \`${section}\`, add a paragraph or table entry within that section.` : "No specific section suggested. Manual mapping required."}

### Option B: Create New Section
If the lesson represents a new failure mode or standard, create a new section tagged with:
- \`[CORE]\` if it applies to all investigations
- \`[FULL AUDIT ONLY]\` if it adds significant overhead
- \`[ADVANCED]\` with an activation trigger

### Option C: Modify Existing Standard
If the lesson reveals that an existing standard is wrong or incomplete:
1. Update the canonical master
2. Run \`node scripts/build.js\` to regenerate derived prompts
3. Run \`node scripts/check-sync.js\` to validate

## Manual Review Checklist
- [ ] Edit is surgical (one concept, one section)
- [ ] All three prompts are updated (or build.js handles propagation)
- [ ] Changelog updated in all three files
- [ ] Version number incremented if structural
- [ ] MDX/escape checks pass for table content
- [ ] No new scoring systems added without explicit approval
- [ ] Anti-hype tone preserved

## After Applying
1. Run \`node scripts/build.js\`
2. Run \`node scripts/check-sync.js\`
3. Commit with: \`git add -A && git commit -m \"vX.Y: [brief description]\"\`
4. Tag: \`git tag vX.Y && git push origin main --tags\`

---
*Proposal generated by Skepsis evolve.js. Human review required.*
`;

  fs.writeFileSync(PROPOSAL, proposal);
  console.log(`📋 Proposal written to proposed-changes.md`);
  console.log("\nNext steps:");
  console.log("  1. Review proposed-changes.md");
  console.log("  2. Apply edits to src/Universal-Debunking-Article-Prompt.md");
  console.log("  3. Run: node scripts/build.js && node scripts/check-sync.js");
}

main();
